/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Patients
         * @description Get a paginated list of patients with optional filtering and sorting.
         *     Uses cursor-based pagination for efficient large dataset handling.
         */
        get: operations["get_patients_api_patients_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/{patient_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Patient By Id
         * @description Get detailed patient information including their appointments.
         */
        get: operations["get_patient_by_id_api_patients__patient_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Providers
         * @description Get a paginated list of providers with appointment counts and revenue.
         *     Uses cursor-based pagination.
         */
        get: operations["get_providers_api_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Patient Analytics
         * @description Get consolidated patient analytics including demographics and sources.
         */
        get: operations["get_patient_analytics_api_analytics_patients_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/business": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Business Analytics
         * @description Get consolidated business analytics including services and appointments.
         */
        get: operations["get_business_analytics_api_analytics_business_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Provider Analytics
         * @description Get top 5 busiest providers by appointment count.
         */
        get: operations["get_provider_analytics_api_analytics_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/patient-behavior": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Patient Behavior Analytics
         * @description Get patient behavior patterns including:
         *     - Distribution of patients by number of appointments (all statuses)
         *     - Top services booked by patients (all appointments)
         */
        get: operations["get_patient_behavior_analytics_api_analytics_patient_behavior_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Health check endpoint.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint for monitoring.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AppointmentWithServices
         * @description Schema for appointment with its services and payment.
         */
        AppointmentWithServices: {
            /** Id */
            id: string;
            /** Patient Id */
            patient_id: string;
            /** Status */
            status: string;
            /** Created Date */
            created_date: string;
            /** Services */
            services: components["schemas"]["ServiceResponse"][];
            payment: components["schemas"]["PaymentResponse"] | null;
        };
        /**
         * BusinessAnalyticsResponse
         * @description Consolidated schema for business analytics (services + appointments).
         */
        BusinessAnalyticsResponse: {
            /** Topservicesbyrevenue */
            topServicesByRevenue: components["schemas"]["ServiceByRevenueResponse"][];
            /** Topservicesbybookings */
            topServicesByBookings: components["schemas"]["ServiceByBookingsResponse"][];
            /** Totalrevenue */
            totalRevenue: number;
            /** Averagepayment */
            averagePayment: number;
            /** Totalcustomers */
            totalCustomers: number;
            /** Statusdistribution */
            statusDistribution: {
                [key: string]: number;
            };
            /** Avgservicesperappointment */
            avgServicesPerAppointment: string;
            /** Appointmentsbyday */
            appointmentsByDay: {
                [key: string]: number;
            };
            /** Totalappointments */
            totalAppointments: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * PatientAnalyticsResponse
         * @description Consolidated schema for patient analytics (demographics + sources).
         */
        PatientAnalyticsResponse: {
            /** Totalpatients */
            totalPatients: number;
            /** Genderdistribution */
            genderDistribution: {
                [key: string]: number;
            };
            /** Agedistribution */
            ageDistribution: {
                [key: string]: number;
            };
            /** Sourcedistribution */
            sourceDistribution: {
                [key: string]: number;
            };
            /** Patientsbymonth */
            patientsByMonth: {
                [key: string]: number;
            };
        };
        /**
         * PatientBehaviorResponse
         * @description Schema for patient behavior analytics.
         */
        PatientBehaviorResponse: {
            /** Patientsbyappointmentcount */
            patientsByAppointmentCount: {
                [key: string]: number;
            };
            /** Topservicesbyrevenue */
            topServicesByRevenue: components["schemas"]["ServiceByRevenueResponse"][];
            /** Topservicesbybookings */
            topServicesByBookings: components["schemas"]["ServiceByBookingsResponse"][];
        };
        /**
         * PatientDetailResponse
         * @description Schema for detailed patient view with appointments.
         */
        PatientDetailResponse: {
            patient: components["schemas"]["PatientResponse"];
            /** Appointments */
            appointments: components["schemas"]["AppointmentWithServices"][];
        };
        /**
         * PatientListResponse
         * @description Schema for paginated patient list.
         */
        PatientListResponse: {
            /** Data */
            data: components["schemas"]["PatientResponse"][];
            /** Nextcursor */
            nextCursor: string | null;
            /** Hasmore */
            hasMore: boolean;
            /** Total */
            total: number;
        };
        /**
         * PatientResponse
         * @description Schema for patient data in API responses.
         */
        PatientResponse: {
            /** Id */
            id: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Date Of Birth */
            date_of_birth: string;
            /** Gender */
            gender: string;
            /** Source */
            source: string;
            /** Address */
            address: string;
            /** Phone */
            phone: string;
            /** Email */
            email: string;
            /** Created Date */
            created_date: string;
        };
        /**
         * PaymentResponse
         * @description Schema for payment data.
         */
        PaymentResponse: {
            /** Id */
            id: string;
            /** Appointment Id */
            appointment_id: string;
            /** Amount */
            amount: number;
            /** Payment Date */
            payment_date: string;
            /** Created Date */
            created_date: string;
        };
        /**
         * ProviderAnalyticsResponse
         * @description Schema for provider analytics (busiest providers).
         */
        ProviderAnalyticsResponse: {
            /** Topproviders */
            topProviders: components["schemas"]["TopProviderResponse"][];
        };
        /**
         * ProviderListResponse
         * @description Schema for paginated provider list.
         */
        ProviderListResponse: {
            /** Data */
            data: components["schemas"]["ProviderResponse"][];
            /** Nextcursor */
            nextCursor: string | null;
            /** Hasmore */
            hasMore: boolean;
            /** Total */
            total: number;
        };
        /**
         * ProviderResponse
         * @description Schema for provider data in API responses.
         */
        ProviderResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Email */
            email: string;
            /** Phone */
            phone: string;
            /** Appointmentcount */
            appointmentCount: number;
            /** Revenue */
            revenue: number;
        };
        /**
         * ServiceByBookingsResponse
         * @description Schema for service ranked by booking count.
         */
        ServiceByBookingsResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Count */
            count: number;
        };
        /**
         * ServiceByRevenueResponse
         * @description Schema for service ranked by revenue.
         */
        ServiceByRevenueResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Revenue */
            revenue: number;
        };
        /**
         * ServiceResponse
         * @description Schema for service data.
         */
        ServiceResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Price */
            price: number;
            /** Duration */
            duration: number;
            /** Created Date */
            created_date: string;
        };
        /**
         * TopProviderResponse
         * @description Schema for top provider item.
         */
        TopProviderResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Email */
            email: string;
            /** Phone */
            phone: string;
            /** Appointmentcount */
            appointmentCount: number;
            /** Revenue */
            revenue: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_patients_api_patients_get: {
        parameters: {
            query?: {
                /** @description Cursor for pagination */
                cursor?: string | null;
                /** @description Number of items per page */
                limit?: number;
                /** @description Search by name, email, or phone */
                search?: string | null;
                /** @description Filter by gender */
                gender?: string | null;
                /** @description Filter by source */
                source?: string | null;
                /** @description Field to sort by */
                sortBy?: string;
                /** @description Sort order (asc or desc) */
                sortOrder?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_patient_by_id_api_patients__patient_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_providers_api_providers_get: {
        parameters: {
            query?: {
                /** @description Cursor for pagination */
                cursor?: string | null;
                /** @description Number of items per page */
                limit?: number;
                /** @description Search by name or email */
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_patient_analytics_api_analytics_patients_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientAnalyticsResponse"];
                };
            };
        };
    };
    get_business_analytics_api_analytics_business_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessAnalyticsResponse"];
                };
            };
        };
    };
    get_provider_analytics_api_analytics_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderAnalyticsResponse"];
                };
            };
        };
    };
    get_patient_behavior_analytics_api_analytics_patient_behavior_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientBehaviorResponse"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
