/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Patients
         * @description Get a paginated list of patients with optional filtering and sorting.
         *     Uses cursor-based pagination for efficient large dataset handling.
         */
        get: operations["get_patients_api_patients_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/{patient_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Patient By Id
         * @description Get detailed patient information including their appointments.
         */
        get: operations["get_patient_by_id_api_patients__patient_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Providers
         * @description Get a paginated list of providers with appointment counts and revenue.
         *     Uses cursor-based pagination.
         */
        get: operations["get_providers_api_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/demographics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Demographics
         * @description Get patient demographics analytics including total patients,
         *     gender distribution, and age distribution.
         */
        get: operations["get_demographics_api_analytics_demographics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sources
         * @description Get patient source analytics including source distribution
         *     and patients by month.
         */
        get: operations["get_sources_api_analytics_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Services Analytics
         * @description Get services analytics including top services, total revenue,
         *     average payment, and total payments.
         */
        get: operations["get_services_analytics_api_analytics_services_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Providers Analytics
         * @description Get providers analytics including appointment counts and revenue per provider.
         */
        get: operations["get_providers_analytics_api_analytics_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/appointments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Appointments Analytics
         * @description Get appointments analytics including status distribution,
         *     average services per appointment, and appointments by day.
         */
        get: operations["get_appointments_analytics_api_analytics_appointments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Health check endpoint.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint for monitoring.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AppointmentWithServices
         * @description Schema for appointment with its services and payment.
         */
        AppointmentWithServices: {
            /** Id */
            id: string;
            /** Patient Id */
            patient_id: string;
            /** Status */
            status: string;
            /** Created Date */
            created_date: string;
            /** Services */
            services: components["schemas"]["ServiceResponse"][];
            payment: components["schemas"]["PaymentResponse"] | null;
        };
        /**
         * AppointmentsAnalyticsResponse
         * @description Schema for appointments analytics.
         */
        AppointmentsAnalyticsResponse: {
            /** Statusdistribution */
            statusDistribution: {
                [key: string]: number;
            };
            /** Avgservicesperappointment */
            avgServicesPerAppointment: string;
            /** Appointmentsbyday */
            appointmentsByDay: {
                [key: string]: number;
            };
            /** Totalappointments */
            totalAppointments: number;
        };
        /**
         * DemographicsResponse
         * @description Schema for demographics analytics.
         */
        DemographicsResponse: {
            /** Totalpatients */
            totalPatients: number;
            /** Genderdistribution */
            genderDistribution: {
                [key: string]: number;
            };
            /** Agedistribution */
            ageDistribution: {
                [key: string]: number;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * PatientDetailResponse
         * @description Schema for detailed patient view with appointments.
         */
        PatientDetailResponse: {
            patient: components["schemas"]["PatientResponse"];
            /** Appointments */
            appointments: components["schemas"]["AppointmentWithServices"][];
        };
        /**
         * PatientListResponse
         * @description Schema for paginated patient list.
         */
        PatientListResponse: {
            /** Data */
            data: components["schemas"]["PatientResponse"][];
            /** Nextcursor */
            nextCursor: string | null;
            /** Hasmore */
            hasMore: boolean;
            /** Total */
            total: number;
        };
        /**
         * PatientResponse
         * @description Schema for patient data in API responses.
         */
        PatientResponse: {
            /** Id */
            id: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Date Of Birth */
            date_of_birth: string;
            /** Gender */
            gender: string;
            /** Source */
            source: string;
            /** Address */
            address: string;
            /** Phone */
            phone: string;
            /** Email */
            email: string;
            /** Created Date */
            created_date: string;
        };
        /**
         * PaymentResponse
         * @description Schema for payment data.
         */
        PaymentResponse: {
            /** Id */
            id: string;
            /** Appointment Id */
            appointment_id: string;
            /** Amount */
            amount: number;
            /** Payment Date */
            payment_date: string;
            /** Created Date */
            created_date: string;
        };
        /**
         * ProviderAnalyticsItem
         * @description Schema for provider analytics item.
         */
        ProviderAnalyticsItem: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Specialty */
            specialty: string;
            /** Appointmentcount */
            appointmentCount: number;
            /** Revenue */
            revenue: number;
        };
        /**
         * ProviderListResponse
         * @description Schema for paginated provider list.
         */
        ProviderListResponse: {
            /** Data */
            data: components["schemas"]["ProviderResponse"][];
            /** Nextcursor */
            nextCursor: string | null;
            /** Hasmore */
            hasMore: boolean;
            /** Total */
            total: number;
        };
        /**
         * ProviderResponse
         * @description Schema for provider data in API responses.
         */
        ProviderResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Email */
            email: string;
            /** Phone */
            phone: string;
            /** Specialty */
            specialty: string;
            /** Appointmentcount */
            appointmentCount: number;
            /** Revenue */
            revenue: number;
        };
        /**
         * ProvidersAnalyticsResponse
         * @description Schema for providers analytics.
         */
        ProvidersAnalyticsResponse: {
            /** Providers */
            providers: components["schemas"]["ProviderAnalyticsItem"][];
        };
        /**
         * ServiceResponse
         * @description Schema for service data.
         */
        ServiceResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Price */
            price: number;
            /** Duration */
            duration: number;
            /** Created Date */
            created_date: string;
        };
        /**
         * ServicesAnalyticsResponse
         * @description Schema for services analytics.
         */
        ServicesAnalyticsResponse: {
            /** Topservices */
            topServices: components["schemas"]["TopServiceResponse"][];
            /** Totalrevenue */
            totalRevenue: number;
            /** Averagepayment */
            averagePayment: number;
            /** Totalpayments */
            totalPayments: number;
        };
        /**
         * SourcesResponse
         * @description Schema for patient sources analytics.
         */
        SourcesResponse: {
            /** Sourcedistribution */
            sourceDistribution: {
                [key: string]: number;
            };
            /** Patientsbymonth */
            patientsByMonth: {
                [key: string]: number;
            };
        };
        /**
         * TopServiceResponse
         * @description Schema for top service item.
         */
        TopServiceResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Count */
            count: number;
            /** Revenue */
            revenue: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_patients_api_patients_get: {
        parameters: {
            query?: {
                /** @description Cursor for pagination */
                cursor?: string | null;
                /** @description Number of items per page */
                limit?: number;
                /** @description Search by name, email, or phone */
                search?: string | null;
                /** @description Filter by gender */
                gender?: string | null;
                /** @description Filter by source */
                source?: string | null;
                /** @description Field to sort by */
                sortBy?: string;
                /** @description Sort order (asc or desc) */
                sortOrder?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_patient_by_id_api_patients__patient_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_providers_api_providers_get: {
        parameters: {
            query?: {
                /** @description Cursor for pagination */
                cursor?: string | null;
                /** @description Number of items per page */
                limit?: number;
                /** @description Search by name or email */
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_demographics_api_analytics_demographics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemographicsResponse"];
                };
            };
        };
    };
    get_sources_api_analytics_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcesResponse"];
                };
            };
        };
    };
    get_services_analytics_api_analytics_services_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServicesAnalyticsResponse"];
                };
            };
        };
    };
    get_providers_analytics_api_analytics_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvidersAnalyticsResponse"];
                };
            };
        };
    };
    get_appointments_analytics_api_analytics_appointments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentsAnalyticsResponse"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
